"""
gen_pkg.py — Generate {proto}_pkg.sv
Structural boilerplate from template + LLM fills protocol-specific types.
"""

SV_12_RULES_NOTE = """
// ─── 12-Rule SV Validation applied during generation ────────────────────
// Rule 1: declarations before statements
// Rule 3: no C++ types (logic not ac_int)
// Rule 8: no hardcoded values (parameters only)
// Rule 9: no $unit scope
"""


def gen_pkg(proto_spec: dict, output_dir: str, llm) -> str:
    """Generate *_pkg.sv from protocol spec."""
    name     = proto_spec['sv_name']
    params   = proto_spec.get('parameters', {})
    channels = proto_spec.get('channels', [])
    txns     = proto_spec.get('transactions', [])

    # Build parameter section
    param_lines = []
    for pname, pval in params.items():
        param_lines.append(f"  parameter int {pname:<20} = {pval};")
    params_sv = '\n'.join(param_lines) if param_lines else '  parameter int DATA_WIDTH = 32;\n  parameter int ADDR_WIDTH = 16;'

    # Build signal width helper (resolve parameter references)
    def resolve_width(w):
        if isinstance(w, int):
            return str(w)
        if isinstance(w, str):
            # e.g. "DATA_WIDTH/8" stays as-is
            return w
        return '1'

    # Build structs for each channel
    struct_lines = []
    for ch in channels:
        ch_name = ch['name'].lower()
        sigs = ch.get('signals', {})
        if not sigs:
            continue
        struct_lines.append(f"\n  // ─── {ch['name']} channel flit ───────────────────────────────")
        struct_lines.append(f"  typedef struct packed {{")
        for sig_name, sig_info in sigs.items():
            w = resolve_width(sig_info.get('width', 1))
            role = sig_info.get('role', '')
            if sig_info.get('role') in ('valid', 'ready'):
                continue  # handshake signals not in struct
            if w == '1' or w == 1:
                struct_lines.append(f"    logic                    {sig_name.lower()};  // {role}")
            else:
                struct_lines.append(f"    logic [{w}-1:0]           {sig_name.lower()};  // {role}")
        struct_lines.append(f"  }} {name}_{ch_name}_t;")

    structs_sv = '\n'.join(struct_lines)

    # Ask LLM for any protocol-specific enums or types
    llm_types = _get_llm_types(proto_spec, llm)

    content = f"""`ifndef {name.upper()}_PKG_SV
`define {name.upper()}_PKG_SV

// {proto_spec.get('description', proto_spec['name'] + ' verification package')}
// Generated by Universal UVM Generator
// Protocol: {proto_spec['name']}
{SV_12_RULES_NOTE}
package {name}_pkg;

  // ─── Protocol parameters ─────────────────────────────────
{params_sv}

  // ─── Protocol-specific types (LLM-generated) ─────────────
{llm_types}

  // ─── Channel transaction structs ─────────────────────────
{structs_sv}

endpackage : {name}_pkg
`endif
"""
    return content


def _get_llm_types(proto_spec: dict, llm) -> str:
    """LLM generates protocol-specific enums and typedefs."""
    challenges = proto_spec.get('verification_challenges', [])
    cov_states = proto_spec.get('coverage_key_states', [])

    prompt = f"""Protocol: {proto_spec['name']}
Description: {proto_spec.get('description', '')}
Key states for coverage: {', '.join(cov_states[:5])}

Generate SystemVerilog typedef enum declarations for this protocol.
Include: response types, state enums, opcode enums — whatever is meaningful for {proto_spec['name']}.
Use ONLY 'typedef enum logic [N:0]' syntax.
Return ONLY the typedef lines, no package declaration, no comments outside the code.
Max 20 lines."""

    result = llm.call(prompt, max_tokens=400)
    if not result:
        return f"  // No protocol-specific types generated"

    # Validate: strip anything that's not a typedef or comment
    lines = []
    for line in result.split('\n'):
        stripped = line.strip()
        if (stripped.startswith('typedef') or
            stripped.startswith('//') or
            stripped.startswith('parameter') or
            stripped.startswith('}') or
            stripped == ''):
            lines.append('  ' + stripped if stripped else '')

    return '\n'.join(lines[:25])
