"""
gen_interface.py — Generate {proto}_if.sv
Pure template — no LLM needed, all info comes from ProtocolSpec channels.
"""


def gen_interface(proto_spec: dict, output_dir: str, llm) -> str:
    """Generate SystemVerilog interface from channel definitions."""
    name     = proto_spec['sv_name']
    channels = proto_spec.get('channels', [])

    # Generate signal declarations grouped by channel
    signal_blocks = []
    for ch in channels:
        ch_name = ch['name']
        sigs    = ch.get('signals', {})
        direction = ch.get('direction', '')
        signal_blocks.append(f"\n  // ─── {ch_name} channel ({direction}) ───────────────────────")
        for sig_name, sig_info in sigs.items():
            w = sig_info.get('width', 1)
            if isinstance(w, int) and w == 1:
                signal_blocks.append(f"  logic                    {sig_name.lower()};")
            else:
                signal_blocks.append(f"  logic [{w}-1:0]           {sig_name.lower()};")

    signals_sv = '\n'.join(signal_blocks)

    content = f"""`ifndef {name.upper()}_IF_SV
`define {name.upper()}_IF_SV

import {name}_pkg::*;

// {proto_spec['name']} SystemVerilog Interface
// Generated by Universal UVM Generator
interface {name}_if (input logic clk);

  logic rst_n;
{signals_sv}

endinterface : {name}_if
`endif
"""
    return content
